on: [pull_request, push]
name: Standard Testset
jobs:
  test:
    name: macOS Default
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install toolchain
        run: |
          pip3 install --user numpy matplotlib shapely
          sudo xcode-select -s /Applications/Xcode_12.2.app
          wget https://storage.googleapis.com/swift-tensorflow-artifacts/macos-toolchains/swift-tensorflow-DEVELOPMENT-2020-08-26-a-osx.pkg
          sudo installer -pkg swift-tensorflow-DEVELOPMENT-2020-08-26-a-osx.pkg -target /
          echo "PATH=/Library/Developer/Toolchains/swift-latest/usr/bin:${PATH}" >> $GITHUB_ENV
      - name: Build
        run: swift build -v
      - name: Test
        run: swift test -v
